# Generated by Django 3.0.5 on 2020-04-29 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=5)),
                ('subdivision', models.CharField(max_length=30)),
                ('birth_date', models.DateField(null=True)),
                ('position', models.CharField(max_length=30)),
                ('experience', models.FloatField(default='0.0')),
                ('shift', models.CharField(max_length=30)),
                ('part_time_job', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=30)),
                ('lateness', models.TimeField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('tasks', models.CharField(blank=True, max_length=500)),
                ('lifespan', models.DurationField(blank=True)),
                ('is_done', models.BooleanField(blank=True, default=False)),
                ('participants', models.ManyToManyField(blank=True, default=None, related_name='participants', to='registration.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(blank=True, max_length=500)),
                ('hour', models.FloatField(blank=True)),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='registration.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='registration.Profile')),
            ],
        ),
    ]
